services:
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/otel-collector-config.yaml"]
    restart: unless-stopped
    volumes:
      - './otel-collector-config.yaml:/otel-collector-config.yaml'
    depends_on:
      - jaeger-all-in-one
    labels:
      - traefik.http.routers.otel-collector.rule=PathPrefix(`/otel-collector`)
      - traefik.http.routers.otel-collector.service=otel-collector
      - traefik.http.routers.otel-collector.middlewares=otel-collector
      - traefik.http.middlewares.otel-collector.stripprefix.prefixes=/otel-collector
      - traefik.http.services.otel-collector.loadbalancer.server.port=4318
    networks:
      - proxy

  jaeger-all-in-one:
    hostname: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - "16686:16686"
    environment:
      - QUERY_BASE_PATH=/jaeger-interface
    labels:
      - traefik.http.routers.jaeger-interface.rule=PathPrefix(`/jaeger-interface`)
      - traefik.http.routers.jaeger-interface.service=jaeger-interface
      - traefik.http.services.jaeger-interface.loadbalancer.server.port=16686
      - traefik.http.routers.jaeger-ingestion.rule=PathPrefix(`/jaeger-ingestion`)
      - traefik.http.routers.jaeger-ingestion.service=jaeger-ingestion
      - traefik.http.routers.jaeger-ingestion.middlewares=jaeger-ingestion
      - traefik.http.middlewares.jaeger-ingestion.stripprefix.prefixes=/jaeger-ingestion
      - traefik.http.services.jaeger-ingestion.loadbalancer.server.port=4318
    networks:
      - proxy

  aws-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    restart: unless-stopped
    volumes:
      - ./aws-collector-config.yaml:/etc/otel-agent-config.yaml
      - C:\Users\cabad\.aws:/home/aoc/.aws
    environment:
      - AWS_REGION=us-east-2
      - AWS_PROFILE=default
    networks:
      - proxy
    labels:
      - traefik.http.routers.aws-collector.rule=PathPrefix(`/aws-collector`)
      - traefik.http.routers.aws-collector.service=aws-collector
      - traefik.http.routers.aws-collector.middlewares=aws-collector
      - traefik.http.middlewares.aws-collector.stripprefix.prefixes=/aws-collector
      - traefik.http.services.aws-collector.loadbalancer.server.port=4318

networks:
    proxy:
        name: proxy
        external: true