services:
  collector:

    image: otel/opentelemetry-collector:latest
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './otel-collector-config.yaml:/otel-collector-config.yaml'
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger-all-in-one

  jaeger-all-in-one:
    hostname: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16685"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  aws-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./aws-collector-config.yaml:/etc/otel-agent-config.yaml
      - C:\Users\cabad\.aws:/home/aoc/.aws
    environment:
      - AWS_REGION=us-east-2
      - AWS_PROFILE=default