receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]

exporters:
  #debug:
  #  verbosity: detailed
  otlphttp/jaeger: # Jaeger supports OTLP directly
    endpoint: http://traefik/jaeger-ingestion
    tls:
      insecure: true
  otlphttp/aws-collector:
    endpoint: http://traefik/aws-collector
    tls:
      insecure: true
  otlphttp/seq:
    endpoint: http://traefik/seq-ingestion/ingest/otlp
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/jaeger, otlphttp/seq, otlphttp/aws-collector]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/seq, otlphttp/aws-collector]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/seq, otlphttp/aws-collector]